<?php

//create new game to play against computer strategy
//need response
//pid <-- ???????

//pid is  unique play identifier generated by web service

//  Upon an error, the web service will notify the client by providing an
//   an appropriate error response like:
//
//     {"response": false, "reason": "Strategy not specified"}
//     {"response": false, "reason": "Unknown strategy"}

//uniqid() -> generate identifier based on current time in microsecond

//Need strategy desing pattern to define STRATEGY CLASS

