<?php

//create new game to play against computer strategy
//need response
//pid <-- ???????

//pid is  unique play identifier generated by web service

//  Upon an error, the web service will notify the client by providing an
//   an appropriate error response like:
//
//     {"response": false, "reason": "Strategy not specified"}
//     {"response": false, "reason": "Unknown strategy"}

//uniqid() -> generate identifier based on current time in microsecond

//Need strategy desing pattern to define STRATEGY CLASS
$url =  dirname(dirname(__FILE__))."/writable/";
define('Strategy',$_GET['strategy']);
print_r($_GET);

$stat = array("Smart", "Random"); // 0 -> Smart 1 ->Random
$game = new Game();
if($_GET == $stat[0] || $_GET == $stat[1]){
    $game->respone = true;
    $game->pid = uniqid();
}else
    $game->response = false;
    $game->reason = "No such strategy";

$board = array(array(0,0,0,0,0,0,0,),array(0,0,0,0,0,0,0,),
    array(0,0,0,0,0,0,0,),array(0,0,0,0,0,0,0,),
    array(0,0,0,0,0,0,0,),array(0,0,0,0,0,0,0,),
    array(0,0,0,0,0,0,0,));
class Game{
    var $response;
    var $pid;
    var $reason;
}



?>
